



ansible_user: WKST
ansible_connection: ssh
ansible_shell_type: cmd
ansible_shell_executable: cmd.exe
ansible_ssh_private_key_file: "~/.ssh/ansible-windows"
remote_tmp: C:/Users/WKST/AppData/Local/Temp/.ansible_tmp

