---
- name: add group
  hosts: win
  gather_facts: false
  tasks:
    - name: Create a new group
      ansible.windows.win_group:
        name: Kastryulya
        description: Deploy Group
        state: present
