---
- name: Add groups to Windows
  hosts: both
  gather_facts: false

  vars:
    groups_list:
      - name: "Sss"
      - name: "Ddd"


  tasks:
#    - name: Debug groups variable
#      debug:
#        var: groups_list

    - name: Create a new group
      ansible.windows.win_group:
        name: "{{ group_item.name }}"
        description: Vip Group
        state: present
      loop: "{{ groups_list }}"
      loop_control:
        loop_var: group_item
