---
- name: add a user
  hosts: win_sup
  gather_facts: false
  tasks:
    - name: add user
      win_user:
        name: "{{item.name}}"
        password: "{{item.password}}"
        password_never_expires: true
        groups: "{{item.groups}}"
        state: present
      loop: "{{ users }}"
