---
- name: add a user
  hosts: win
  gather_facts: false
  tasks:
    - name: add user
      win_user:
        name: pelmen
        password: "Welcome123"
        password_never_expires: true
        account_expires: never
        groups: Kastryulya
        state: present
