---
- name: add a user
  hosts: win
  gather_facts: false
  tasks:
    - name: Create a new group
      ansible.windows.win_group:
        name: SuperAnsiGroup
        description: Deploy Group
        state: present
