---
- name: Remove user
  hosts: "{{ target_host }}"
  gather_facts: false

  vars_files:
    - group_vars/remove_user.yml

  tasks:
    - name: Del user
      ansible.windows.win_user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        state: absent
      loop: "{{ users }}"












